// Fluxo CRM — dados fictícios do seed
// Nomes inventados de propósito (nenhum cliente real do Gabriel aparece
// aqui) para que o seed possa ser rodado e resetado sem risco de misturar
// com dados de produção. Segmentos batem com o que a Fluxo realmente
// prospecta (advogado, pousada, restaurante, tatuagem, clínica, loja...).

export type SeedLead = {
  company_name: string;
  contact_name: string;
  segment_key: string;
  city: string;
  state: string;
  whatsapp: string;
  instagram: string;
  website_url?: string;
  google_maps_url?: string;
  source_key: string;
  has_website: boolean;
  website_quality: "none" | "very_bad" | "bad" | "average" | "good";
  pilot_created: boolean;
  pilot_url?: string;
  stage_key: string;
  temperature: "hot" | "warm" | "cold" | "none";
  estimated_value: number;
  prospectedDaysAgo: number;
  tags?: string[];
  note?: string;
  // se definido, o lead já nasce fechado e vira cliente no seed
  willConvert?: boolean;
  lossReasonKey?: string;
  lossNotes?: string;
};

export const SEED_LEADS: SeedLead[] = [
  {
    company_name: "Andrade & Rocha Advocacia",
    contact_name: "Fernanda Andrade",
    segment_key: "lawyer",
    city: "Tiradentes",
    state: "MG",
    whatsapp: "5532999110001",
    instagram: "@andraderocha.adv",
    website_url: "https://andraderocha.adv.br",
    source_key: "google_maps",
    has_website: true,
    website_quality: "bad",
    pilot_created: true,
    pilot_url: "https://piloto-andraderocha.vercel.app",
    stage_key: "proposal_sent",
    temperature: "hot",
    estimated_value: 2400,
    prospectedDaysAgo: 12,
    tags: ["Advogado", "Site antigo"],
    note: "Sócia decide sozinha, prefere falar depois das 18h.",
  },
  {
    company_name: "Pousada Vale Verde",
    contact_name: "Marcos Tavares",
    segment_key: "inn",
    city: "Tiradentes",
    state: "MG",
    whatsapp: "5532999110002",
    instagram: "@pousadavaleverde",
    source_key: "instagram_prospecting",
    has_website: false,
    website_quality: "none",
    pilot_created: true,
    pilot_url: "https://piloto-valeverde.vercel.app",
    stage_key: "meeting_scheduled",
    temperature: "warm",
    estimated_value: 1800,
    prospectedDaysAgo: 6,
    tags: ["Pousada", "Sem site"],
    note: "Muito interessado no piloto, quer reserva online integrada.",
  },
  {
    company_name: "Sabor da Serra Restaurante",
    contact_name: "Ivete Campos",
    segment_key: "restaurant",
    city: "São João del-Rei",
    state: "MG",
    whatsapp: "5532999110003",
    instagram: "@sabordaserra",
    source_key: "instagram",
    has_website: false,
    website_quality: "none",
    pilot_created: false,
    stage_key: "prospected",
    temperature: "none",
    estimated_value: 1200,
    prospectedDaysAgo: 1,
  },
  {
    company_name: "Tato Estúdio de Tatuagem",
    contact_name: "Diego Fontes",
    segment_key: "tattoo_studio",
    city: "Tiradentes",
    state: "MG",
    whatsapp: "5532999110004",
    instagram: "@tato.estudio",
    website_url: "https://tatoestudio.com",
    source_key: "referral",
    has_website: true,
    website_quality: "very_bad",
    pilot_created: true,
    pilot_url: "https://piloto-tato.vercel.app",
    stage_key: "negotiation",
    temperature: "hot",
    estimated_value: 1600,
    prospectedDaysAgo: 18,
    tags: ["Tatuador", "Alto potencial"],
    note: "Pediu desconto à vista, negociando forma de pagamento.",
  },
  {
    company_name: "Clínica Bem Estar",
    contact_name: "Dra. Patrícia Lemos",
    segment_key: "clinic",
    city: "São João del-Rei",
    state: "MG",
    whatsapp: "5532999110005",
    instagram: "@clinicabemestar",
    source_key: "google_maps",
    has_website: true,
    website_quality: "average",
    pilot_created: false,
    stage_key: "qualifying",
    temperature: "warm",
    estimated_value: 2200,
    prospectedDaysAgo: 4,
  },
  {
    company_name: "Móveis Bragança",
    contact_name: "Roberto Bragança",
    segment_key: "store",
    city: "Tiradentes",
    state: "MG",
    whatsapp: "5532999110006",
    instagram: "@moveisbraganca",
    source_key: "networking",
    has_website: false,
    website_quality: "none",
    pilot_created: false,
    stage_key: "to_contact",
    temperature: "cold",
    estimated_value: 1400,
    prospectedDaysAgo: 3,
  },
  {
    company_name: "Barbearia Nobre",
    contact_name: "Wesley Nunes",
    segment_key: "service_provider",
    city: "São João del-Rei",
    state: "MG",
    whatsapp: "5532999110007",
    instagram: "@barbearianobre",
    source_key: "whatsapp",
    has_website: false,
    website_quality: "none",
    pilot_created: true,
    pilot_url: "https://piloto-nobre.vercel.app",
    stage_key: "contacted",
    temperature: "warm",
    estimated_value: 900,
    prospectedDaysAgo: 5,
  },
  {
    company_name: "Doce Ponto Confeitaria",
    contact_name: "Juliana Prado",
    segment_key: "local_business",
    city: "Tiradentes",
    state: "MG",
    whatsapp: "5532999110008",
    instagram: "@docepontoconfeitaria",
    source_key: "instagram_prospecting",
    has_website: false,
    website_quality: "none",
    pilot_created: true,
    pilot_url: "https://piloto-doceponto.vercel.app",
    stage_key: "responded",
    temperature: "hot",
    estimated_value: 1100,
    prospectedDaysAgo: 2,
    tags: ["Alto potencial"],
    note: "Respondeu na hora, adorou o piloto.",
  },
  {
    company_name: "Oliveira Odontologia",
    contact_name: "Dr. Caio Oliveira",
    segment_key: "clinic",
    city: "São João del-Rei",
    state: "MG",
    whatsapp: "5532999110009",
    instagram: "@oliveiraodonto",
    source_key: "google_maps",
    has_website: true,
    website_quality: "average",
    pilot_created: true,
    pilot_url: "https://piloto-oliveira.vercel.app",
    stage_key: "lost",
    temperature: "cold",
    estimated_value: 2000,
    prospectedDaysAgo: 25,
    lossReasonKey: "price",
    lossNotes: "Achou o valor alto comparado ao concorrente.",
  },
  {
    company_name: "Estúdio Fit Pilates",
    contact_name: "Renata Suzano",
    segment_key: "service_provider",
    city: "Tiradentes",
    state: "MG",
    whatsapp: "5532999110010",
    instagram: "@fitpilatesestudio",
    source_key: "instagram",
    has_website: false,
    website_quality: "none",
    pilot_created: false,
    stage_key: "prospected",
    temperature: "none",
    estimated_value: 1000,
    prospectedDaysAgo: 0,
  },
  {
    company_name: "Ateliê Costura Fina",
    contact_name: "Marlene Aguiar",
    segment_key: "local_business",
    city: "Tiradentes",
    state: "MG",
    whatsapp: "5532999110011",
    instagram: "@costurafina",
    source_key: "referral",
    has_website: false,
    website_quality: "none",
    pilot_created: true,
    pilot_url: "https://piloto-costurafina.vercel.app",
    stage_key: "proposal_sent",
    temperature: "warm",
    estimated_value: 950,
    prospectedDaysAgo: 9,
  },
  {
    company_name: "Malbec Vinhos & Cia",
    contact_name: "Eduardo Malbec",
    segment_key: "store",
    city: "Tiradentes",
    state: "MG",
    whatsapp: "5532999110012",
    instagram: "@malbecvinhos",
    source_key: "past_client",
    has_website: false,
    website_quality: "none",
    pilot_created: true,
    pilot_url: "https://piloto-malbec.vercel.app",
    stage_key: "won",
    temperature: "hot",
    estimated_value: 1700,
    prospectedDaysAgo: 40,
    willConvert: true,
  },
  {
    company_name: "Hotel Pousada do Lago",
    contact_name: "Simone Vilela",
    segment_key: "inn",
    city: "Tiradentes",
    state: "MG",
    whatsapp: "5532999110013",
    instagram: "@pousadadolago",
    source_key: "referral",
    has_website: true,
    website_quality: "bad",
    pilot_created: true,
    pilot_url: "https://piloto-pousadalago.vercel.app",
    stage_key: "won",
    temperature: "hot",
    estimated_value: 2600,
    prospectedDaysAgo: 55,
    willConvert: true,
  },
  {
    company_name: "Reis & Castro Advogados",
    contact_name: "Bruno Castro",
    segment_key: "lawyer",
    city: "São João del-Rei",
    state: "MG",
    whatsapp: "5532999110014",
    instagram: "@reiscastroadv",
    source_key: "linkedin",
    has_website: true,
    website_quality: "very_bad",
    pilot_created: true,
    pilot_url: "https://piloto-reiscastro.vercel.app",
    stage_key: "won",
    temperature: "warm",
    estimated_value: 2900,
    prospectedDaysAgo: 70,
    willConvert: true,
  },
  {
    company_name: "Cantina Bella Vista",
    contact_name: "Antonio Bellini",
    segment_key: "restaurant",
    city: "Tiradentes",
    state: "MG",
    whatsapp: "5532999110015",
    instagram: "@cantinabellavista",
    source_key: "instagram_prospecting",
    has_website: false,
    website_quality: "none",
    pilot_created: true,
    pilot_url: "https://piloto-bellavista.vercel.app",
    stage_key: "won",
    temperature: "hot",
    estimated_value: 1500,
    prospectedDaysAgo: 35,
    willConvert: true,
  },
];

export const SEED_LEAD_NAMES = SEED_LEADS.map((l) => l.company_name);
